language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pecl install -f curl
  - phpenv config-add test/resources/php.ini

install:
  - composer install

script:
  - vendor/bin/phing build
