language: php
php:
  - 5.5
  - 5.6

before_script:
  - phpenv config-add test/resources/php.ini

install:
  - composer install

script:
  - vendor/bin/phing build

after_script:
  - travis_retry php vendor/bin/coveralls -v
